/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shared Run */
        get: operations["get_shared_run_api_share__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/framing/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refine Framing */
        post: operations["refine_framing_api_runs__run_id__framing_refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/framing/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Framing */
        post: operations["confirm_framing_api_runs__run_id__framing_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roster */
        get: operations["roster_api_roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seats */
        get: operations["seats_api_seats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Schema
         * @description Exists so the RunEvent union is part of the OpenAPI document for type generation.
         */
        get: operations["event_schema_api_schema_event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run */
        get: operations["export_run_api_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactRecord */
        ArtifactRecord: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "brief" | "market_research" | "ledger" | "problem_validation" | "pr_v1" | "pr_v2" | "internal_faq" | "concept_validation" | "pr_v3" | "external_faq" | "prfaq" | "bar_raiser" | "plan";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            /** Created At */
            created_at: string;
            /** Key Insight */
            key_insight: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** BarRaiserOutput */
        BarRaiserOutput: {
            /** Scores */
            scores: components["schemas"]["Score"][];
            /** Overall */
            overall: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "revise";
            /** Required Fixes */
            required_fixes: components["schemas"]["Fix"][];
            /** Key Insight */
            key_insight: string;
        };
        /**
         * Claim
         * @description A factual or quantitative statement inside a slot and where it comes from.
         */
        Claim: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "evidence" | "assumption";
            /** Finding Ids */
            finding_ids: string[];
        };
        /** ConfirmFramingRequest */
        ConfirmFramingRequest: {
            framing?: components["schemas"]["Framing"] | null;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Idea */
            idea: string;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
        };
        /** DocumentVersionEvent */
        DocumentVersionEvent: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document.version";
            /** Version */
            version: number;
            /** Artifact Id */
            artifact_id: string;
            /**
             * Produced By Seat
             * @enum {string}
             */
            produced_by_seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            press_release: components["schemas"]["PressRelease"];
            /** Edits */
            edits: components["schemas"]["Edit"][];
            /** Caption */
            caption: string | null;
        };
        /**
         * Edit
         * @description One change to one slot, with the reason and the evidence behind it.
         */
        Edit: {
            /**
             * Slot Id
             * @enum {string}
             */
            slot_id: "headline" | "subheading" | "summary" | "problem" | "solution" | "benefits" | "internal_quote" | "cta";
            /** New Text */
            new_text: string;
            /** Rationale */
            rationale: string;
            /** Evidence Finding Ids */
            evidence_finding_ids: string[];
            /**
             * Change Kind
             * @enum {string}
             */
            change_kind: "sharpen" | "clarify" | "reground" | "cut" | "restructure" | "polish";
        };
        /**
         * EventEnvelope
         * @description Wrapper so the union appears in the OpenAPI components for type generation.
         */
        EventEnvelope: {
            /** Event */
            event: components["schemas"]["RunStarted"] | components["schemas"]["FramingReady"] | components["schemas"]["RunStatusChanged"] | components["schemas"]["StepStarted"] | components["schemas"]["StepProgress"] | components["schemas"]["StepTool"] | components["schemas"]["StepDelta"] | components["schemas"]["StepThinking"] | components["schemas"]["StepCompleted"] | components["schemas"]["StepFailed"] | components["schemas"]["DocumentVersionEvent"] | components["schemas"]["RunBudgetWarning"] | components["schemas"]["RunCompleted"] | components["schemas"]["RunFailed"] | components["schemas"]["RunCancelled"];
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Claim */
            claim: string;
            /** Metric */
            metric: string | null;
            /**
             * Topic
             * @enum {string}
             */
            topic: "market_size" | "competition" | "customer" | "pricing" | "trend" | "regulation" | "barrier" | "success_factor" | "other";
            /** Source Ids */
            source_ids: string[];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /** Fix */
        Fix: {
            /** Target */
            target: string;
            /** Instruction */
            instruction: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "important";
        };
        /** Framing */
        Framing: {
            /** Working Name */
            working_name: string;
            /** Target Customer */
            target_customer: string;
            /** Customer Problem */
            customer_problem: string;
            /** Product Scope */
            product_scope: string;
        };
        /** FramingReady */
        FramingReady: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "framing.ready";
            framing: components["schemas"]["Framing"];
            /** Attempt */
            attempt: number;
            /** Key Insight */
            key_insight: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** Provider Ready */
            provider_ready: boolean;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Database */
            database: string;
            /** Version */
            version: string;
        };
        /** PersonaRecord */
        PersonaRecord: {
            /**
             * Id
             * @enum {string}
             */
            id: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Initials */
            initials: string;
            /** Hue */
            hue: number;
            /** Seats */
            seats: ("0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10")[];
            /** How I Review */
            how_i_review: string;
        };
        /** PressRelease */
        PressRelease: {
            /** Slots */
            slots: components["schemas"]["Slot"][];
        };
        /** RefineFramingRequest */
        RefineFramingRequest: {
            /**
             * Target Customer
             * @default
             */
            target_customer: string;
            /**
             * Customer Problem
             * @default
             */
            customer_problem: string;
            /**
             * Product Scope
             * @default
             */
            product_scope: string;
        };
        /** RunBudgetWarning */
        RunBudgetWarning: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.budget_warning";
            /** Spent Usd */
            spent_usd: number;
            /** Ceiling Usd */
            ceiling_usd: number;
        };
        /** RunCancelled */
        RunCancelled: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled";
        };
        /** RunCompleted */
        RunCompleted: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.completed";
            /** Prfaq Artifact Id */
            prfaq_artifact_id: string;
            /** Plan Artifact Id */
            plan_artifact_id: string;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Duration S */
            duration_s: number;
            bar_raiser: components["schemas"]["BarRaiserOutput"] | null;
        };
        /** RunFailed */
        RunFailed: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.failed";
            /** Error */
            error: string;
        };
        /** RunListItem */
        RunListItem: {
            /** Id */
            id: string;
            /** Idea */
            idea: string;
            /**
             * Status
             * @enum {string}
             */
            status: "framing" | "awaiting_confirmation" | "running" | "completed" | "failed" | "cancelled";
            /** Headline */
            headline: string | null;
            /** Working Name */
            working_name: string | null;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunRecord */
        RunRecord: {
            /** Id */
            id: string;
            /** Idea */
            idea: string;
            /**
             * Status
             * @enum {string}
             */
            status: "framing" | "awaiting_confirmation" | "running" | "completed" | "failed" | "cancelled";
            framing: components["schemas"]["Framing"] | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Error */
            error: string | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Share Token */
            share_token: string | null;
            /** Headline */
            headline: string | null;
        };
        /** RunSnapshot */
        RunSnapshot: {
            run: components["schemas"]["RunRecord"];
            /** Steps */
            steps: components["schemas"]["StepRecord"][];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactRecord"][];
            /** Versions */
            versions: components["schemas"]["VersionRecord"][];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            bar_raiser: components["schemas"]["BarRaiserOutput"] | null;
            /** Last Seq */
            last_seq: number;
            /** Roster */
            roster: components["schemas"]["PersonaRecord"][];
            /** Seats */
            seats: components["schemas"]["SeatRecord"][];
        };
        /** RunStarted */
        RunStarted: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
            /** Idea */
            idea: string;
        };
        /** RunStatusChanged */
        RunStatusChanged: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.status";
            /**
             * Status
             * @enum {string}
             */
            status: "framing" | "awaiting_confirmation" | "running" | "completed" | "failed" | "cancelled";
        };
        /** Score */
        Score: {
            /**
             * Criterion
             * @enum {string}
             */
            criterion: "customer_clarity" | "problem_specificity" | "anecdote_believability" | "v1_feasibility" | "differentiation" | "evidence_coverage" | "executive_readability";
            /** Score */
            score: number;
            /** Note */
            note: string;
        };
        /** SeatRecord */
        SeatRecord: {
            /**
             * Id
             * @enum {string}
             */
            id: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Name */
            name: string;
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            /**
             * Produces
             * @enum {string}
             */
            produces: "brief" | "market_research" | "ledger" | "problem_validation" | "pr_v1" | "pr_v2" | "internal_faq" | "concept_validation" | "pr_v3" | "external_faq" | "prfaq" | "bar_raiser" | "plan";
            /** Depends On */
            depends_on: ("brief" | "market_research" | "ledger" | "problem_validation" | "pr_v1" | "pr_v2" | "internal_faq" | "concept_validation" | "pr_v3" | "external_faq" | "prfaq" | "bar_raiser" | "plan")[];
            /** Phase */
            phase: string;
            /** Tier */
            tier: string;
        };
        /** Slot */
        Slot: {
            /**
             * Id
             * @enum {string}
             */
            id: "headline" | "subheading" | "summary" | "problem" | "solution" | "benefits" | "internal_quote" | "cta";
            /** Text */
            text: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Cited Text */
            cited_text: string;
        };
        /** StepCompleted */
        StepCompleted: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.completed";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Artifact Id */
            artifact_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "brief" | "market_research" | "ledger" | "problem_validation" | "pr_v1" | "pr_v2" | "internal_faq" | "concept_validation" | "pr_v3" | "external_faq" | "prfaq" | "bar_raiser" | "plan";
            /** Key Insight */
            key_insight: string | null;
            usage: components["schemas"]["Usage"];
            /** Duration S */
            duration_s: number;
            /** Cost Usd */
            cost_usd: number;
            /** Model */
            model: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Attempt */
            attempt: number;
        };
        /** StepDelta */
        StepDelta: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.delta";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Text */
            text: string;
        };
        /** StepFailed */
        StepFailed: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.failed";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Error */
            error: string;
            /** Retryable */
            retryable: boolean;
            /** Attempt */
            attempt: number;
        };
        /** StepProgress */
        StepProgress: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.progress";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Note */
            note: string;
        };
        /** StepRecord */
        StepRecord: {
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Name */
            name: string;
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Model */
            model: string;
            /** Effort */
            effort: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Duration S */
            duration_s: number | null;
            usage: components["schemas"]["Usage"];
            /** Cost Usd */
            cost_usd: number;
            /** Fallback Used */
            fallback_used: boolean;
            /** Error */
            error: string | null;
            /** Key Insight */
            key_insight: string | null;
        };
        /** StepStarted */
        StepStarted: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.started";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Name */
            name: string;
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            /** Model */
            model: string;
            /** Effort */
            effort: string;
            /** Attempt */
            attempt: number;
            /** Activity */
            activity: string[];
        };
        /** StepThinking */
        StepThinking: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.thinking";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /** Text */
            text: string;
        };
        /** StepTool */
        StepTool: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.tool";
            /**
             * Seat
             * @enum {string}
             */
            seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /**
             * Kind
             * @enum {string}
             */
            kind: "search" | "fetch";
            /** Query */
            query: string | null;
            /** Url */
            url: string | null;
        };
        /** Usage */
        Usage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Cache Creation Input Tokens
             * @default 0
             */
            cache_creation_input_tokens: number;
            /**
             * Cache Read Input Tokens
             * @default 0
             */
            cache_read_input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Web Searches
             * @default 0
             */
            web_searches: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionRecord */
        VersionRecord: {
            /** Version */
            version: number;
            /** Artifact Id */
            artifact_id: string;
            /**
             * Produced By Seat
             * @enum {string}
             */
            produced_by_seat: "0" | "1" | "1b" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "9b" | "10";
            /**
             * Persona
             * @enum {string}
             */
            persona: "strategist" | "analyst" | "researcher" | "pm" | "vp_product" | "biz_eng" | "customer_success" | "editor" | "bar_raiser" | "validation_lead";
            press_release: components["schemas"]["PressRelease"];
            /** Edits */
            edits: components["schemas"]["Edit"][];
            /** Caption */
            caption: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_run_api_share__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_framing_api_runs__run_id__framing_refine_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineFramingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_framing_api_runs__run_id__framing_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmFramingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roster_api_roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaRecord"][];
                };
            };
        };
    };
    seats_api_seats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatRecord"][];
                };
            };
        };
    };
    event_schema_api_schema_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventEnvelope"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_runs__run_id__export_get: {
        parameters: {
            query?: {
                format?: string;
                from_version?: number;
                to_version?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
